server:
  port: 0
  servlet:
    context-path: /user
  compression:
    enabled: true
    mime-types: application/json,application/x-protobuf
spring:
  application.name: user-service
  couchbase:
    username: Administrator
    password: 666666
    bucket-name: medium
    host: ${COUCHBASE_SERVER:127.0.0.1}
    port: 8091
  main:
    banner-mode: off
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER:http://localhost:8761/admin}

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
     defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

sentry:
  dsn: ${SENTRY_DSN}
  in-app-includes: org.medium.user
  send-default-pii: on
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

grpc:
  client:
    cloud-grpc-server:
      address: 'discovery:///cloud-grpc-server'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext