server:
  port: 0
  servlet:
    context-path: /article

spring:
  application.name: article-service
  couchbase:
    username: Administrator
    password: 666666
    bucket-name: medium
    host: ${COUCHBASE_SERVER:127.0.0.1}
    port: 8091

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

