apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: micro-medium-gateway
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: EUREKA_SERVER
            value: http://eureka-server.default.svc.cluster.local:8761/eureka
          - name: _JAVA_OPTS
            value: -Deureka.instance.preferIpAddress=true
