apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: localhost:5000/micro-medium-service-discovery
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8761
#        env:
#          - name: _JAVA_OPTS
#            value: -Deureka.instance.preferIpAddress=true -Deureka.instance.hostname=eureka-server -Deureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
