apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: shevchyk/micro-medium-user
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: EUREKA_URL
            value: http://eureka-server-service:8761/eureka
