server:
  port: 8088

spring:
  artemis:
    mode: embedded
    embedded:
      enabled: true
  cloud:
    stream:
      bindings:
        articleCreated-in-0.destination: articleCreated
      binder:
        brokers: localhost:9092
