global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user_medium_scrape'
    metrics_path: '/USER-SERVICE/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.141:8080']
  - job_name: 'article_medium_scrape'
    metrics_path: '/ARTICLE-SERVICE/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.141:8080']